### ISSUE TITLE
oXs_out_frsky.cpp: current cast error on hub protocol

### ISSUE THREAD

**Issue by manuprendlair** [openXsensor/openXsensor#17]
Hello, 

I found an error in the code with the cast when sending current with DEFAULTFIELD in hub protocol:

You write ligne 1187:

 SendCurrentMilliAmps(( ( (int16_t) currentData->milliAmps \* fieldContainsData[currentFieldToSend][2] / fieldContainsData[currentFieldToSend][3]) ) + fieldContainsData[currentFieldToSend][4]);

but this is not working correctly, (test for example with a milliAmps = 45000, set in the oXs_curr.cpp)

you must write:

 SendCurrentMilliAmps( (int32_t) (currentData->milliAmps \* fieldContainsData[currentFieldToSend][2] / fieldContainsData[currentFieldToSend][3])  + fieldContainsData[currentFieldToSend][4]);

Have a nice day!

Emmanuel
From France

**Comment by mstrens** [comment]
Has been fixed in version 7 (or perhpas already before)
