### ISSUE TITLE
oXs ver.7.0 MPX protocol GPS

### ISSUE THREAD

**Issue by nostromo123** [openXsensor/openXsensor#20]
Just did a desktop test with GPS under MPX protokol.

![bildschirmfoto5](https://cloud.githubusercontent.com/assets/17964433/18816058/76956be0-8341-11e6-9615-6280afad31d9.jpeg)

This is the output part in  oXs_config.h 

_// ****\* 9.3 - Multiplex data *****
# define SETUP_MULTIPLEX_DATA_TO_SEND    \

```
                    4 , GPS_COURSE , 1 , 1 , 0 , -16384 , 16383 , \
                    5 , GPS_SPEED , 1 , 1 , 0 , -16384 , 16383 , \
                    6 , GPS_ALTITUDE , 1 , 1 , 0 , -16384 , 16383 , \
                    7 , GPS_DISTANCE , 1 , 1 , 0 , -16384 , 16383 , \
                    8 , GPS_BEARING , 1 , 1 , 0 , -16384 , 16383_
```

![bildschirmfoto6](https://cloud.githubusercontent.com/assets/17964433/18816060/7c2451b6-8341-11e6-8634-a998bce566fc.jpeg)
![bildschirmfoto7](https://cloud.githubusercontent.com/assets/17964433/18816062/7f9f9788-8341-11e6-94bc-a15ed95955ad.jpeg)

**In postition #7 on display should it not be 0.7 _m_ instead of 0.7 _km_?**

br KH

**Comment by nostromo123** [comment]
Could be, that km is ok, but then this line in oXs_config_description.h might be wrong

*    GPS_DISTANCE      0.1 m     Distance from home 

Must be km instead of m here??

**Comment by mstrens** [comment]
oXs calculates gps distance in m.
There is a bug in a line from oXs_multiplex.h
In V7 and before, there is 
                        MU_VOLT , MU_CURR , MU_MAH , MU_DIR , MU_ASPD , MU_ALT , MU_RPM , MU_DIST , MU_DIR ,  MU_LEVEL ,\
It should be 
                        MU_VOLT , MU_CURR , MU_MAH , MU_DIR , MU_ASPD , MU_ALT , MU_RPM , MU_ALT , MU_DIR ,  MU_LEVEL ,\ 

I will fix it in next version (= version 8)
