### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by RCdiy** [openXsensor/openXsensor#25]
Had a thought while working with Bernd.
Can you modify the GPS code to optionally use a Compass attached to the Arduino for its heading?
This way when using on a transmitter (taranis, s.port) the pilot can rotate in one spot and the heading would update as well...

**Comment by mstrens** [comment]
This is implemented in the next version. Bernd is testing it.

**Comment by RCdiy** [comment]
Thanks. Your Rock!
