### ISSUE TITLE
Error in Compiler when activating current sensor

### ISSUE THREAD

**Issue by onki69** [openXsensor/openXsensor#28]
[oXs_config.zip](https://github.com/openXsensor/openXsensor/files/1049576/oXs_config.zip)

Hi,

when I activate the currentsensor in the code in line:
`#define PIN_CURRENTSENSOR   6`

I get the following error when compiling the code.
`exit status 1
no match for 'operator=' (operand types are 'ONE_MEASUREMENT' and 'int')`

Problem is labelled in this line:
`  oXs_Current.currentData.consumedMilliAmps = 0;`

Any idea what is wrong?

Best regards
Onki

**Comment by mstrens** [comment]
This is normally fixed in the latest version.
