### ISSUE TITLE
ADS not installed and ADS_MEASURE || ADS_CURRENT_BASED_ON defined

### ISSUE THREAD

**Issue by 3djc** [openXsensor/openXsensor#34]
Since aug 19th, the 'default' oXs_config_advanced.h enables ADS_MEASURE and ADS_CURRENT_BASED_ON, which creates issues if no ADS1115 is installed (at least in some setup)

Quite a few sensors subdefinitions are 'protected'  by a main define, like A_MPU6050_IS_CONNECTED, but none exist for ADS1115

**Comment by mstrens** [comment]
I changed the default config (to disable ADS_MEASURE) and I added a few more YES/NO options in oXs_config_basic.h
I hope this will help avoiding config mistakes
