### ISSUE TITLE
Flow Sensor reset not possible with pushbutton and PPM signal using Jeti protocol

### ISSUE THREAD

**Issue by onki69** [openXsensor/openXsensor#39]
Sorry for creating so many issues but it probably helps to make OXS perferct for all protocols.
I did several tests with the flow sensor using the Jeti protocol with my DC16.
Since navigating through the Jetibox is not really nice (especially when using a Jeti Transmitter) I like the idea to reset the fuel consumption using the external pushbutton method (at I/O 10 to GND) or through the PPM signal level.

Both versions do not seem to work with the Jeti protocol although I think resetting values is not very protocol specific.
Save to EEPROM was activated and works as this will enable the pushbutton AFAIK.
PPM detection seem to work as well as I did some tests using the Sequencer.
Would be great if someone could review the code to check that out.
Thanks
Onki
P.S. Is there a specific forum to discuss OXS specific issues?

**Comment by mstrens** [comment]
I tested the ppm with Jeti protocol and it works.
Note do not use the sequencer at the same time because when sequencer is activated, ppm signal is used only for the sequencer.
For reset per push button I enlarged the time window (press between 3 and 8 sec but not more)
