### ISSUE TITLE
Current display continuous 0 ampere

### ISSUE THREAD

**Issue by hobby1946** [openXsensor/openXsensor#46]
Hello,
This OXS V7 version works . Current and voltage are displayed. 

But this does not work with the V8.
Here not Cels is displayed, but Vfas.
Fvas is fine. Curr is always 0.0A

Which is probably the mistake, Vfas and Curr have the same Sub-ID 3. That can't work.

If I set the voltage measurement to "NO" (basic.h),
you can no longer compile OXS because an error message appears with which I can
but can't do anything.

Define ARDUINO_MEASURES_VOLTAGES NO 
then:
error When VFAS_SOURCE is VOLT_1, VOLT_2,... VOLT_6 then PIN_VOLTAGE must be defined too.

greatings
berny

**Comment by nostromo123** [comment]
@ mstrens.

Hi, we are discussing that issue here in German forum

https://fpv-community.de/threads/openxsensor-gps-funktioniert-nicht.83430/page-4#post-1025636

Might have a look there.

br
