### ISSUE TITLE
openXsensor and FrOS

### ISSUE THREAD

**Issue by knudj** [openXsensor/openXsensor#55]
Dear all,

I would like to do a general telemetry project using Arduino, FrSky X8R and FrSky Horus X12S.

Would openXsensor work for the FrSky Operating System FrOS or do I need to change it to OpenTX?

As I see the telemetry sensor names are pre-set in FrOS and I wonder whether I can address them (e.g. "Analog1-4") from openXsensor.

Thanks a lot for your help

Knud

**Comment by mstrens** [comment]
I am sorry but I have no experience with FrOS.
oXs uses the standard ID used by the Frsky sensors a few years ago.
So I presume that their FrOS supports them.
Anyway, it is also possible to change the ID used by oXs
