### ISSUE TITLE
Does TTL9600 GPS module work?

### ISSUE THREAD

**Issue by MatsAndT** [openXsensor/openXsensor#56]
Does it work with the TTL9600 https://banggood.app.link/7GCwmfw6h6 GPS module?

**Comment by mstrens** [comment]
I am not sure it will work.
oXs needs that the chip supports the UBLOX neo6M, neo7m or neo8m protocols.
oXs does not uses the NEMA messages at 9600 bauds but sent commands to reconfigures the GPS to UBLOX messages at 38200 bauds
