### ISSUE TITLE
#define DEBUG has been removed

### ISSUE THREAD

**Issue by nostromo123** [openXsensor/openXsensor#58]
#define DEBUG has been removed in actual version.

Please put it in again.

br KH

**Comment by mstrens** [comment]
it is still there but it is moved to the file oXs_config_macros.h (which is called by all the other files)

**Comment by nostromo123** [comment]
Thank you for making that clear. Good to know. 
Still struggling with Jim with his oXs problems.

br KH

**Comment by nostromo123** [comment]
But could you add a note in oXs_config_description.h please?

**Comment by mstrens** [comment]
I just did it.
