### ISSUE TITLE
 Increase voltage resolution with oversampling & decimation

### ISSUE THREAD

**Issue by universam1** [openXsensor/openXsensor#6]
Hi,

I would like to suggest a technique to drastically improve the voltage reading accuracy beyond the hardware limit of 10bit. Especially this would be helpfull for higher volatages for batteries >3S where the high voltage divider needs better resolution to archieve usefull readings.

Atmel describes this really smart idea at http://www.atmel.com/Images/doc8003.pdf
Basically noise (which we have enough) is used to oversample and decimate to higher resolution. From my experience you can easily archieve 12-14bits without any hardware change. 
This is [b]NOT to be mixed with smoothing or averaging[/b] like it is used currently in the code!

Other projects where Lipo battery voltage is read uses this technique too, like charger: https://github.com/stawel/cheali-charger/blob/master/docs/artificial_adc_noise.md

There is a nice tested implementation available as a library here: https://github.com/ElectricRCAircraftGuy/eRCaGuy_analogReadXXbit/tree/Version_2

From my tests I would suggest to use 12bits readings at least and can confirm its usefullness! The good point is that this replaces smoothing per se and would require not too much adjustment. The tricky part is here not to loose the gained resolution by simple downscaling later. Therefore the calculation of the divider must be done with the new higher resolution! Of course the oversampling takes time but we are averaging anyway. 
Actually, when it is not desirable to use the above library it could be possible to implement that with only small adjustments to the code.

What do you think?

Thx Sam

**Comment by mstrens** [comment]
oXs already does oversampling in order to get more accurate data. 
From version 8 it is even possible to add an ADS1115 (external ADC with 15/16 bits and preamplifier) to increase even more accuracy
