### ISSUE TITLE
error caused by newer MPU6050 which have a revision number higher than 2

### ISSUE THREAD

**Issue by ChrisOhara57** [openXsensor/openXsensor#65]
File:  inv_mpu.c
Routine: mpu_init()
New MPU Sensors have higher revisions  (mine has rev=4).
So I had to insert ||rev=4  to prevent mpu_init() to return with error status.
I do not know if there  are other  revisions higher than 2 out for sale?

if (rev) {
        if (rev == 1)                         chip_cfg.accel_half = 1;
        else if (rev == 2 || rev == 4)        chip_cfg.accel_half = 0;

**Comment by Willi-Billi** [comment]
Dear all,

Maybe I have also this problem. When I have in the configuration the GY86 as first baro and the MPU is off, then the
Vario works, that means, the data go's to the TX.

When is switch the MPU on, then I don't have any telemetrie values from the baro.

Is this maybe the same storry ?

One smal question: What is the way to find the revision of the GY86 ?

Kind regards 
Willi
