### ISSUE TITLE
Request: Add GPS Date & Time (smartport)

### ISSUE THREAD

**Issue by Hobby4life** [openXsensor/openXsensor#68]
I like to request date and time from GPS

**Comment by romoloman** [comment]
Hi I have implemented the request in my own fork.
Have a look and let me know if it works for you.

**Comment by Hobby4life** [comment]
Will let you know.. will test tonight :-)

**Comment by romoloman** [comment]
To enable the feature you can generate the config using the configurator or define GPS_TRANSMIT_TIME in osx_config_advanced.h

**Comment by ParkerEde** [comment]
Hi romoloman,
sounds great. Where can I get your fork to test it?
Will you also implement it in the regular repo?

**Comment by romoloman** [comment]
click on my icon and have a look to my repositories. You will find openXsensor.
I have done several modifications to openXsensor expecially in the oxsconfigurator and also to the vario (to be able to get air temperature) I don't know if it's a good idea to push commit in regular repository.

**Comment by romoloman** [comment]
BTW I plan to add date/time also to sensor hub telemetry by implementing frame3 packet.
(i still have some D8 receiver around)

**Comment by ParkerEde** [comment]
it works perfect. BIG Thank you. 
One additional question. Does it make sense to reduce the transmission interval for DateTime on the sport to once per second?

**Comment by Hobby4life** [comment]
That would indeed be better. Dont know the timeout limit for date and time. But as long as possible intervals.

**Comment by romoloman** [comment]
well i have vario, voltages, gps, in my case It's already less than 1 second but we can reduce the 1 per second by keeping previous trasmitted value and transmit it only when value change (so 1 per second for time and 1 per day for date).

**Comment by Hobby4life** [comment]
Interval of 1sec for now is fine for both Date and Time.

**Comment by romoloman** [comment]
Committed... please check.

**Comment by ParkerEde** [comment]
with the new version, I got no DateTime anymore.

#define GPS_TRANSMIT_TIME is active in oXs_config_advanced.h

**Comment by romoloman** [comment]
ok i will check this night with a sensor available...

**Comment by Hobby4life** [comment]
I have tested your first firmware, and the interval there is very acceptable for me :-) 500mS?
And works with ETHOS ;-)

**Comment by romoloman** [comment]
within one hour or two I will be able to make some test with the sensor,
Probably my last commit should work, but i'm not sure.
Previous one was broken as I did it while doing something else :(.....

**Comment by Hobby4life** [comment]
> within one hour or two I will be able to make some test with the sensor, Probably my last commit should work, but i'm not sure. Previous one was broken as I did it while doing something else :(..... BTW did you testes also oxsconfigurator ? I have implemented almost all the tabs including sequencer.

I have seen it added the GPS TIME definition, so thats works.. but did not compiled with the generated files.
I have manually added the definition to my configs.

**Comment by romoloman** [comment]
Ok latest commit slow down TIME and date trasmission, and it works.

**Comment by ParkerEde** [comment]
Fantasitic. It works great. I added manually the line
#define GPS_TRANSMIT_TIME 
to my oXs_config_advanced.h.
I've done one test with the Windows Configurator, this works well.

All my GPS Sensors are already flashed now with your fork. Very very thank you.

Kind regards
ParkerEde

**Comment by romoloman** [comment]
Hi ParkerEde, have a look to the latest commit, it avoid a stupid call to millis() so maybe your GPS_TRANSMIT_TIME becomes useless.
Calling millis() uses a lot of bytes, the last commit instead set data available only when seconds changes so once per second, and that's enough.

**Comment by ParkerEde** [comment]
okay, thank you. I applied the last commit. Looks good. My GPS Sensors are now updated.

**Comment by romoloman** [comment]
"I also had a fix regarding negative current over smartport. ETHOS does not like this."
It's already in my fork, as well a fix regarding BMP280
